# An example file with explanations. Some options can be left to None, but others are required
programs:                                 #a list of programs
    program:                                              #the name of a program *Required*
        cmd: "ls -l R /"                      #the exact command to launch *Required*
        cmdammount: 1                                     #the number of times you need to launch this process *Required*
        autostart: True                       #cmd started at launch True/False? *Required*
        autorestart: "never"                                #restart this program on "never", "always", or on "unexpected" termination *Required*
        starttime: 5                                     #amount of time to go by before the program is considered "succesfully started" *Required*
        stoptime: 10                          #amount of time to go by after sending quitsit to program before killing it completely with SIGKILL *Required*
        restartretries: 3                     #amount of times a program will be tried to be restarted or started at the beginning before giving up on it *Required*
        quitsig: TERM                                    #signal that will be sent to the command to be gracefully exited (QUIT, TERM, INT, KILL) *Required*
        exitcodes:                            #exitcodes that define an expected termination for use autorestart or None for all exitcodes being considered unexpected
            - 0
            - 2
            - 15
        workingdir: "/Users/abe/Desktop/"                #working directory to be set for the command or None for same working dir as parent(taskmaster)
        umask: 022                            #umask to be set for the program or None
        stdout: "/dev/random"                            #option to redirect stdout to file or to simple discard it with "discard" or None
        stderr: "/dev/random"                  #option to redirect stderr to file or to simple discard it with "discard" or None
        env:                                             #extra env parameters to provide to the new process or None
            - STARTED_BY=TASKMASTER
            - ANSWER=42