programs:
    sleep:
        cmd: "sleep 10"
        cmdammount: 5
        autostart: True
        autorestart: "never"
        starttime: 5
        stoptime: 10
        restartretries: 3
        quitsig: TERM
        exitcodes: None
        workingdir: "/tmp/"
        umask: 777
        stdout: None
        stderr: None
        env: None
    ls:
        cmd: "ls -l /"
        cmdammount: 3
        autostart: True
        autorestart: "unexpected"
        starttime: 5
        stoptime: 10
        restartretries: 3
        quitsig: TERM
        exitcodes:
            - 0
            - 2
            - 15
        workingdir: "/Users/abe/Desktop/"
        umask: 022
        stdout: "outfile.log"
        stderr: "outfile.log"
        env:
            - STARTED_BY=TASKMASTER
            - ANSWER=42
    pwd:
        cmd: "pwd"
        cmdammount: 20
        autostart: True
        autorestart: "unexpected"
        starttime: 5
        stoptime: 10
        restartretries: 3
        quitsig: TERM
        exitcodes:
            - 0
            - 2
            - 15
        workingdir: "/Users/abe/Desktop/"
        umask: 022
        stdout: None
        stderr: None
        env: None