programs:
    sleep:
        cmd: "sleep 1000"
        cmdammount: 10
        autostart: True
        autorestart: "never"
        starttime: 5
        stoptime: 10
        restartretries: 3
        quitsig: TERM
        exitcodes: None
        workingdir: "/tmp/"
        umask: 000
        stdout: None
        stderr: None
        env: None
    ls:
        cmd: "ls -lR /"
        cmdammount: 1
        autostart: False
        autorestart: "unexpected"
        starttime: 5
        stoptime: 10
        restartretries: 3
        quitsig: TERM
        exitcodes: None
        workingdir: "/Users/abguimba/Desktop/"
        umask: None
        stdout: "outfile.log"
        stderr: "outfile.log"
        env:
            - STARTED_BY=TASKMASTER
            - ANSWER=42
    env:
        cmd: "env"
        cmdammount: 1
        autostart: True
        autorestart: "unexpected"
        starttime: 5
        stoptime: 10
        restartretries: 3
        quitsig: TERM
        exitcodes:
            - 0
            - 2
            - 15
        workingdir: None
        umask: 022
        stdout: "/Users/abguimba/Desktop/caca"
        stderr: None
        env:
            - STARTED_BY=TASKMASTER
            - ANSWER=42